name: Terratest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: "**/*.sum"
          go-version: '1.21.3'

      - name: Download modules
        working-directory: test
        run: go mod tidy

      - name: Test Terraform
        working-directory: test
        run: go test -v
